spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jeremw264/books-microservice-spring
          default-label: develop
server:
  port: 9190

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9105/eureka/
